CREATE TABLE civilization_stats (
    id_civilization NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    wood_amount NUMBER DEFAULT 5000,
    iron_amount NUMBER DEFAULT 5000,
    food_amount NUMBER DEFAULT 5000,
    mana_amount NUMBER DEFAULT 5000,
    magicTower_level NUMBER DEFAULT 1,
    church_level NUMBER DEFAULT 1,
    farm_level NUMBER DEFAULT 1,
    smithy_level NUMBER DEFAULT 1,
    woodsman_level NUMBER DEFAULT 1,
    ironMine_level NUMBER DEFAULT 1
);
