CREATE TABLE civilization_stats (
    id_civilization NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    wood_amount NUMBER DEFAULT 5000,
    iron_amount NUMBER DEFAULT 5000,
    food_amount NUMBER DEFAULT 5000,
    mana_amount NUMBER DEFAULT 5000,
    magicTower_level NUMBER DEFAULT 1,
    church_level NUMBER DEFAULT 1,
    farm_level NUMBER DEFAULT 1,
    smithy_level NUMBER DEFAULT 1,
    woodsman_level NUMBER DEFAULT 1,
    ironMine_level NUMBER DEFAULT 1
);

-- TABLA DE UNIDADES DE ATAQUE
CREATE TABLE attack_units_stats (
    id_unit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_civilization NUMBER,
    unit_type VARCHAR2(30), -- Aquí irá 'Swordsman' o 'Spearman'
    armor NUMBER,
    base_damage NUMBER,
    experience NUMBER DEFAULT 0,
    sanctified NUMBER(1) DEFAULT 0, -- 0 es NO, 1 es SI
    CONSTRAINT fk_civ_attack FOREIGN KEY (id_civilization) REFERENCES civilization_stats(id_civilization)
);

-- TABLA DE UNIDADES DE DEFENSA
CREATE TABLE defense_units_stats (
    id_unit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_civilization NUMBER,
    unit_type VARCHAR2(30), -- Aquí irá 'ArrowTower' o 'Catapult'
    armor NUMBER,
    experience NUMBER DEFAULT 0,
    sanctified NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_civ_defense FOREIGN KEY (id_civilization) REFERENCES civilization_stats(id_civilization)
);